#Data source 
#Indica el driver/lib para conectar java a mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Url donde esta el servicio de tu mysql y el nombre de la base de datos
#spring.datasource.url = jdbc:mysql://remotemysql.com:3306/GP9Y5q4O8J
#spring.datasource.username = GP9Y5q4O8J
#spring.datasource.password = fb7bBPJx5R
spring.datasource.url=jdbc:mysql://localhost/umbrella_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=gonchamania

#[Opcional]Imprime en tu consola las instrucciones hechas en tu base de datos.
spring.jpa.show-sql = true

#Crea/actualiza las tablas automaticamente al iniciar.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect